
-- First, let's clear the existing courses with numeric IDs and insert them with proper UUIDs
DELETE FROM public.courses WHERE id IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10');

-- Insert the courses with proper UUID format
INSERT INTO public.courses (id, title, description, image_url, price, original_price, duration, mode, age_range, category) VALUES
(gen_random_uuid(), 'Art & Craft Classes', 'Explore creativity through various art and craft activities. Perfect for developing artistic skills and imagination.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/fd7df4fd-8fe5-4faa-9801-d3aabccc5157.png', 1500, 2000, '4 weeks', 'Offline', '6-16 years', 'Creative'),
(gen_random_uuid(), 'Spoken English Class', 'Master fluent English communication and build confidence in speaking with native-like fluency.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/ab749e7b-7e24-4d9e-b411-43bc73b0ed39.png', 1999, 2999, '8 weeks', 'Hybrid', '10+ years', 'Language'),
(gen_random_uuid(), 'Spoken Hindi Class', 'Learn to speak Hindi fluently with proper pronunciation and grammar for effective communication.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/c07edaf9-7666-4790-8fd5-aa7c87e82621.png', 1799, 2499, '6 weeks', 'Offline', '8+ years', 'Language'),
(gen_random_uuid(), 'Soft Skill Training', 'Develop essential soft skills for personal and professional success in todays competitive world.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/d25e1c5a-1fb9-4781-add1-43899f865741.png', 3499, 4999, '4 weeks', 'Online', '15+ years', 'Professional'),
(gen_random_uuid(), 'Public Speaking', 'Overcome stage fear and become a confident public speaker with proven techniques and practice.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/9a4c6801-fcf4-4a3e-958c-116d313d908d.png', 2499, 3499, '3 weeks', 'Offline', '12+ years', 'Communication'),
(gen_random_uuid(), 'Personality Development Class', 'Transform your personality and build self-confidence for personal and professional growth.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/eea1d960-780b-4db1-89ab-648014f584d0.png', 2999, 4499, '6 weeks', 'Hybrid', '14+ years', 'Personal Development'),
(gen_random_uuid(), 'Career Counseling', 'Get expert guidance for career planning and make informed decisions about your future path.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/96cfbc73-aed1-4bef-9de8-5b597d0e461f.png', 1999, 2999, '2 sessions', 'Online', '16+ years', 'Counseling'),
(gen_random_uuid(), 'Health Insurance', 'Understand health insurance policies and make the right choices for you and your familys wellbeing.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/beb09b19-fd17-434b-8096-e9a42a070078.png', 999, 1499, '1 session', 'Online', '18+ years', 'Insurance'),
(gen_random_uuid(), 'Tarot Reading', 'Discover insights into your life path through professional tarot card reading sessions.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/8b5de2fa-aca2-40f2-9170-0af6794ef7fc.png', 1299, 1999, '1 session', 'Offline', '18+ years', 'Spiritual'),
(gen_random_uuid(), 'Business Consulting', 'Get expert advice for starting and growing your business with proven strategies and insights.', 'https://raw.githubusercontent.com/softskillmam/kiki-learn-grow-21/main/public/lovable-uploads/aab35988-5b49-4486-86d5-cc8a330fd4c9.png', 4999, 7499, '3 sessions', 'Hybrid', '21+ years', 'Business');
