// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syhwdpvhoydnpajyxcpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5aHdkcHZob3lkbnBhanl4Y3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODM4OTYsImV4cCI6MjA2Njk1OTg5Nn0.GItRmz_P2odp36p_AOsVTWuQMBILMFcodmDiLK2_zBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});